In [2]:
import numpy as np

In [3]:
array = np.array(range(10))

In [4]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
array_2d = np.array([range(10),range(10)])
array_2d + 1

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [6]:
array_2d

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [7]:
array.shape

(10,)

In [8]:
array_2d.shape

(2, 10)

In [9]:
array.size

10

In [10]:
array_2d.size

20

In [11]:
array_2d.T

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5],
       [6, 6],
       [7, 7],
       [8, 8],
       [9, 9]])

In [12]:
array_2d.T.size

20

In [13]:
array_2d.T.shape

(10, 2)

In [14]:
array.dtype

dtype('int64')

In [15]:
array_2d.dtype

dtype('int64')

Assignment 1
NumPy Arrays
A NumPy array, 'age_array' has been created from a list of ages.
Store the size of the array in the variable 'size', and the shape of the array in the variable 'shape', then print both variables.

In [16]:
#Sample Code Provided
import numpy as np

age_list = [22, 34, 57, 65, 87, 19, 44]

age_array = np.array(age_list)

Answer

In [17]:
import numpy as np

age_list = [22, 34, 57, 65, 87, 19, 44]

age_array = np.array(age_list)

size = age_array.size
shape = age_array.shape

print(size)
print(shape)

7
(7,)


Convert List to Array using Numpy

In [18]:
my_list = [x * 10 for x in range(1,11)]
my_list = np.array(my_list)
my_list.shape
my_list.size

10

In [19]:
my_list

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [20]:
my_list.shape

(10,)

In [21]:
my_list.size

10

In [22]:
my_list.ndim

1

reshape the array

In [23]:
my_array = np.array(my_list).reshape(2,5) # 2 rows 5 columns reshaped

In [24]:
my_array

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100]])

Array Creation
    np.ones
    np.zeros
    np.arrange
    np.linespace
    np.array.reshape

In [25]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [26]:
np.ones(5,dtype=int)

array([1, 1, 1, 1, 1])

In [27]:
np.zeros(100,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [28]:
np.zeros((5,20),dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [29]:
np.identity(10).T

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])